Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,8 +20,19 @@ jobs:
           chmod +x plugin.sh
           echo "Running UnRAID-Plugin-Generator:"
           # ./plugin.sh
+          CONFIG_FILE="./plugin.cfg"
+          if [[ -f "$CONFIG_FILE" ]]; then
+            . $CONFIG_FILE
+          else
+            echo "Config file not found: $CONFIG_FILE"
+            exit 1
+          fi
+          
+          OUTPUT_FILE="${config['name']:1:-1}.plg"
           rm plugin.sh
           pwd
+          echo ${CONFIG_FILE}
+          echo ${OUTPUT_FILE}
           ls -ls
       - name: Commit changes
         uses: EndBug/add-and-commit@v9
